# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PILImage.numpy": "00_core.ipynb",
         "PILImage.cv2": "00_core.ipynb",
         "RLE": "02_utils.ipynb",
         "RLE.decode": "02_utils.ipynb",
         "RLE.to_bbox": "02_utils.ipynb"}

modules = ["core.py",
           "utils.py"]

doc_url = "https://lgvaz.github.io/detectrino/"

git_url = "https://github.com/lgvaz/detectrino/tree/master/"

def custom_doc_links(name): return None
