# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"patch_classmethod": "00_core.ipynb",
         "PILImage.numpy": "00_core.ipynb",
         "PILImage.cv2": "00_core.ipynb",
         "RLE": "01_data.core.ipynb",
         "RLE.decode": "01_data.core.ipynb",
         "RLE.to_bbox": "01_data.core.ipynb",
         "DataCfg": "01_data.core.ipynb",
         "Record": "01_data.core.ipynb",
         "Info": "01_data.core.ipynb",
         "Annotation": "01_data.core.ipynb",
         "BBox": "01_data.core.ipynb",
         "from_xyxy_abs": "01_data.core.ipynb",
         "from_rle": "01_data.core.ipynb",
         "Seg": "01_data.core.ipynb",
         "from_polys": "01_data.core.ipynb",
         "ModelCatalog": "05_model.external.ipynb"}

modules = ["core.py",
           "data/core.py",
           "model/external.py"]

doc_url = "https://lgvaz.github.io/detectrino/"

git_url = "https://github.com/lgvaz/detectrino/tree/master/"

def custom_doc_links(name): return None
