# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['patch_classmethod']

# Cell
from fastai2.vision.all import *

# Cell
def patch_classmethod(f):
    cls = next(iter(f.__annotations__.values()))
    return patch_to(cls, cls_method=True)(f)

# Cell
@patch
def numpy(self:PILImage): return np.array(self)
@patch
def cv2(self:PILImage): return self.numpy()[..., ::-1]