# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastai2.vision.all import *

# Cell
@patch
def numpy(self:PILImage): return np.array(self)
@patch
def cv2(self:PILImage): return self.to_np()[..., ::-1]