# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_model.config.ipynb (unless otherwise specified).

__all__ = ['ModelCfg', 'RCNNCfg']

# Cell
from ..basics import *

# Cell
class ModelCfg(Cfg):
    def __init__(self, mfile, n_class): self.mfile,self.n_class = mfile,n_class
    def to_cfg(self): return {'MODEL': {'ROI_HEADS': {'NUM_CLASSES': self.n_class}}}

# Cell
class RCNNCfg(ModelCfg):
    def __init__(self, mfile, n_class, bs_per_img=None):
        super().__init__(mfile, n_class)
        self.bs_per_img = bs_per_img

    def to_cfg(self):
        cfg = {'MODEL': {'ROI_HEADS': {'BATCH_SIZE_PER_IMAGE': self.bs_per_img}}}
        return mergedicts(super().to_cfg(), cfg)